# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

AWSTemplateFormatVersion: 2010-09-09
Description: my-test-app
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 100
    MemorySize: 128
    Runtime: nodejs14.x
    Handler: index.handler
    Environment:
      Variables:
        MY_TASKS_TABLE: !Ref MyTasksTable
Parameters:
  StageName:
    Type: String
    Default: dev
Resources:
  MyTasksApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      OpenApiVersion: "3.0.3"
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !GetAtt LambdaAuthorizerFunction.Arn
            Identity:
              ValidationExpression: Bearer.*
              ReauthorizeEvery: 0
  #### USER RELATED RESOURCES ####
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/user/get-user/
      Description: A Lambda function that returns a user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref UserLayer
        - !Ref GenericLayer
      Events:
        GetUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: GET
            Path: /users/{userId}
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/user/create-user/
      Description: A Lambda function that creates a user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref UserLayer
        - !Ref GenericLayer
      Events:
        CreateUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: POST
            Path: /users
            Auth:
              Authorizer: NONE
  PatchUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/user/patch-user/
      Description: A Lambda function that patches a user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref UserLayer
        - !Ref GenericLayer
      Events:
        PatchUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: PATCH
            Path: /users/{userId}
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/user/delete-user/
      Description: A Lambda function that delete a user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref UserLayer
        - !Ref GenericLayer
      Events:
        DeleteUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: DELETE
            Path: /users/{userId}
  ### AUTH RELATED RESOURCES ####
  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/lambda-authorizer/
      Description: A Lambda function that checks if the user is authorized to access the API
      Environment:
        Variables:
          JWT_SECRET: ""
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/login/
      Description: A Lambda function that logs in a user
      Environment:
        Variables:
          JWT_SECRET: ""
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref UserLayer
        - !Ref GenericLayer
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: POST
            Path: /auth/signin
            Auth:
              Authorizer: NONE
  #### LIST RELATED RESOURCES ####
  CreateListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/list/create-list/
      Description: A Lambda function that creates a list for the specified user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref ListLayer
        - !Ref GenericLayer
      Events:
        CreateListApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: POST
            Path: /users/{userId}/lists
  GetListsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/list/get-lists/
      Description: A Lambda function that gets the lists of the specified user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref ListLayer
        - !Ref GenericLayer
      Events:
        GetListsApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: GET
            Path: /users/{userId}/lists/
  DeleteListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/list/delete-list/
      Description: A Lambda function that delete a list of the specified user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref ListLayer
        - !Ref GenericLayer
      Events:
        DeleteListApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: DELETE
            Path: /users/{userId}/lists/{listId}
  #### TASK RELATED RESOURCES ####
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/task/create-task/
      Description: A Lambda function that creates a task for the specified user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref TaskLayer
        - !Ref GenericLayer
      Events:
        CreateTaskApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: POST
            Path: /lists/{listId}/tasks
  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/task/get-tasks/
      Description: A Lambda function that gets the tasks of the specified list
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref TaskLayer
        - !Ref GenericLayer
      Events:
        GetTasksApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: GET
            Path: /lists/{listId}/tasks/
  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/task/update-task/
      Description: A Lambda function that updates a task for the specified user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref TaskLayer
        - !Ref GenericLayer
      Events:
        UpdateTaskApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: PUT
            Path: /lists/{listId}/tasks/{taskId}
  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/task/delete-task/
      Description: A Lambda function that deletes a task of the specified user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTasksTable
      Layers:
        - !Ref DynamoLayer
        - !Ref TaskLayer
        - !Ref GenericLayer
      Events:
        DeleteTaskApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyTasksApi
            Method: DELETE
            Path: /lists/{listId}/tasks/{taskId}
  ### LAYERS ###
  DynamoLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DynamoLayer
      Description: Dependency for DynamoDB related functions
      ContentUri: layers/dynamo-layer
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x
  ListLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ListLayer
      Description: Dependency for List Model related functions
      ContentUri: layers/list-layer
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x
  TaskLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: TaskLayer
      Description: Dependency for Task Model related functions
      ContentUri: layers/task-layer
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x
  UserLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: UserLayer
      Description: Dependency for User Model related functions
      ContentUri: layers/user-layer
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x
  GenericLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GenericLayer
      Description: Dependency for Generic functions
      ContentUri: layers/generic-layer
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x
  MyTasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user-email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
